### ISSUE TITLE
Setup BibXML data using Relaton-IEEE

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-data-ieee#1]
The ietf-ribose/ieee-rawbib repository requires authenticated access. The following GHA secrets should be used to access it:

* `IETF_RIBOSE_CI_PAT`: GitHub token for the CI user
* `IETF_RIBOSE_CI_USERNAME`: GitHub username for the CI user

**Comment by andrew2net** [comment]
Done
