### ISSUE TITLE
Data in this repository should be in BibXML format

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-data-ieee#2]
@andrew2net the data in this repository should only be in BibXML format, not in Relaton YAML.

**Comment by andrew2net** [comment]
Fixed

**Comment by ronaldtse** [comment]
Thank you @andrew2net !

**Comment by ronaldtse** [comment]
@andrew2net where is the workflow for updating this repo? I can't seem to find it, thanks.

**Comment by ronaldtse** [comment]
@andrew2net ah I see it now it's in this repo. However, we want to separate the workflow from this repo as this repo should only deal with data.

Maybe we should move it to another repository...
