### ISSUE TITLE
Update data file naming scheme and review data schema according to old implementation

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-data-ieee#3]
In the old BibXML format, the filename formats were like this:

```
https://xml2rfc.tools.ietf.org/public/rfc/bibxml-ieee/reference.IEEE.802-3.1990.xml
```

We may want to update this repo from:
* 802_3-1998.xml
* to 802-3.1998.xml

As shown here:
https://ieeexplore.ieee.org/document/720570/versions#versions
<img width="601" alt="Screenshot 2021-09-30 at 1 53 45 AM" src="https://user-images.githubusercontent.com/11865/135322713-de3d3b63-36b7-4ed4-884e-439bb6c6de60.png">

NOTE: this file actually contains mistaken content. There is no 802-3 document in 1990 about LAN. While this one refers to a "2nd edition", the 2nd edition was published in 1998 (https://github.com/ietf-ribose/bibxml-data-ieee/blob/main/data/802_3-1998.xml), and there is another document 802i-3 in 1990 but it was about metropolitan access networks.

**Comment by ronaldtse** [comment]
The filenames should be generated according to this implementation:
https://trac.ietf.org/trac/xml2rfc/browser/website/rfcs/bibxml/bibxml-ieee

**Comment by andrew2net** [comment]
> The filenames should be generated according to this implementation:
> https://trac.ietf.org/trac/xml2rfc/browser/website/rfcs/bibxml/bibxml-ieee

@ronaldtse I didn't find a filenames generator in the implementation. The script seems just fetch files from FTP and these file names are just numbers with xml or zip extension.
We can use RegEx to retrieve a part number and a year from a document identifier and generate needed file names.

**Comment by ronaldtse** [comment]
@andrew2net the filename pattern is produced here:

https://trac.ietf.org/trac/xml2rfc/browser/website/rfcs/bibxml/bibxml-ieee/gen-bibxml-ieee-gen-bibxml
```py
stdnumber = bibxml_common.get_xml_text(root, './publicationinfo/stdnumber')

...

mod_stdnumber = re.sub('_+', '_', re.sub(r'[/,\'" ]', '_', stdnumber))
bibxml_file = f"{args.bibxml_dir}/reference.IEEE.{mod_stdnumber}.xml"
```

**Comment by andrew2net** [comment]
@ronaldtse  it's my bad, I looked for a local file name generator. However, the pattern won't transform the stdnumber from `802.3-1998` to `802-3.1998`. It just replaces some chars with an underscore as shown in the example:
```
# filename: reference.IEEE.802.16M_2011.xml
#        <publication><publicationinfo><stdnumber>802.16m-2011 => IEEE.802.16M_2011
```
You can see the stdnumber in the source file ieee-rawbib/cache/IEEEstd/1998/5830/15560/00720570.xml
To do the transformation we need to parse number (802), part (3), and year (1998) from `802.3-1998` then compile a new stdnumber `{number}-{part}.{year}`. The only question is what chars number and part could contain? Are they number only or can have letters as well?

**Comment by ronaldtse** [comment]
@andrew2net I'm not sure what you mean by:

> However, the pattern won't transform the stdnumber from 802.3-1998 to 802-3.1998. It just replaces some chars with an underscore as shown in the example

The original example mentioned was actually from the old bibxml-ieee library. The new bibxml-ieee library is at:
https://xml2rfc.tools.ietf.org/public/rfc/bibxml-ieee-new/

And in fact, the new numbering is different so it is in a pattern that looks reasonable:
```
/reference.IEEE.802.3-1985.xml
/reference.IEEE.802.3-1998.xml
/reference.IEEE.802.3-2000.xml
/reference.IEEE.802.3-2002.xml
/reference.IEEE.802.3-2005.xml
/reference.IEEE.802.3-2005_Cor_1-2006.xml
/reference.IEEE.802.3-2005_Cor_2-2007.xml
/reference.IEEE.802.3-2008.xml
/reference.IEEE.802.3-2008_Cor_1-2009.xml
/reference.IEEE.802.3-2012.xml
/reference.IEEE.802.3-2015.xml
/reference.IEEE.802.3-2015_Cor_1-2017.xml
/reference.IEEE.802.3-2018.xml
```

Can you investigate this issue in detail and provide a summary?

1. Determine the patterns used previously for IEEE:
    1. (old bibxml-ieee that we may want to support) https://xml2rfc.tools.ietf.org/public/rfc/bibxml-ieee/
    2. (new bibxml-ieee, but we don't have to support this) https://xml2rfc.tools.ietf.org/public/rfc/bibxml-ieee-new/
2. Describe the differences between (i.) and (ii.).
3. Figure out whether the pattern (i.) makes sense. We will want to support this legacy path as closely as we can (in the API), but if there are elements that don't make sense, we will still want to name the files in a consistent way.
4. Provide a recommendation.

In addition, can you help investigate the bibxml-ieee implementation I provided to ensure we are not missing any details in our implementation (IEEE -> Relaton-IEEE, Relaton-IEEE -> BibXML).

**Comment by andrew2net** [comment]
1. Patterns:

i. `reference.IEEE.{number}-{part}.{year}` or
`reference.IEEE.{number}.{part}.{subpart}_{conform}_{year}_{cor}_{ed}` or
`reference.IEEE.{number}_{part}_{year}_{amd}` or
`reference.IEEE.ISO_IEC_{number}_{part}_{year}_{number}.{part}_{year}` or
`reference.IEEE.ISO_IEC_{number}_IEEE_STD_{number}_{year}` or
`reference.IEEE.ISO_IEC_{number}_IEEE_STD_{number}_{year}_FIRST_EDITION_{date}`
- `{number}` is a set of digits and optional letters
- `{part}` is a set of 1 or 2 digits and optional letters; starts with a digit; if a letter or letters are present then they are in the end; optional
- `{subpart}` is a digit and optionally followed by a letter; optional
- `{conform}` is conformance with the pattern `CONFORMANCE{confnum}` where `{confnum}` is 2 digits number; optional
- `{year}` is a set of 4 digits; optional
- `{cor}` is a corrigendum with the pattern `COR_{cornum}_{year}` or `COR{cornum}_{year}` where `{cornum}` is a digit; optional
- `{ed}` is an edition with the pattern `EDITION_ISO_IEC_TR{number}_{part}_{year}_` or `EDITION`; optional
- `{amd}` is an amendment with the pattern `AMD.{amdnum}_{year}` where `{amdnum}` is a digit; optional
- `{date}` is a date with pattern `{year}_{month}_{day}` where `{month}` and `{day}` are 2 digits numbers

ii. `reference.IEEE.{number}.{part}.{subpart}.{subpart}-{year}_{cor}` or
`reference.IEEE.{number}-{part}-{year}` or
`reference.IEEE.{number}_{number}.{part}_{number}-{year}` or
`reference.IEEE.{number}_{number}.{part}.{subpart}-{year}` or
`reference.IEEE.{number}-{part}:{year}_{amd}-{year}` or
`reference.IEEE.{number}-{part}:{year}_IEEE_Std_{number}.{part}-{year}` or
`reference.IEEE.{number}-{year}_IEEE_Std_{number}.{part}-{year}`
```regex
{
^reference\.IEEE\.
(?<number>[A-z0-9]+|(\d{3}_)?Self-Study_Course(_\(IEEE_Red_Book\))?)
(?<parts>([.-][A-Z]?\d{1,3}[A-z]*\d?|-\d{5}[a-z]?|\.\d[a-z](_[a-z])*|-A|-STD-\d{3}|[A-Z]\d{4}|_[A-Z]\d)*
(?<edition>_INT|-CONC|[-_]Conformance\d{2}|_Edition|_\d{3}\.\d[a-z]|_CSA_[A-Z]\d{2,3}\.\d(_No\.\d{3}\.\d)?)?
(?<date>([-_:.]|_-|_[A-Z][a-z]{2}_)\d{4})?)+
(?<correction>((_Cor[_.]?|[_-](?i)Amd(?-i)([_.]|\._)?)\d{1,2}(_[A-Z]\d\.\d)?|_IEEE_Std_\d{4}\.\d|_\d{5}-\d{3}(\.\d)?)((:|-|:-|_[A-Z][a-z]{2}_)\d{4}(-\d{4})?)?)?
(?<other>_(First_Edition_2007-07_IEEE_930|Battery_Life_Improvement|Handbook_\(sixth_edition\)|EQ_Sourcebook:))?$
}x
```
- `{number}` is a set of one or more digits and optional letters
- `{part}` is a set of 1, 2, or 5 digits and optional letters; starts with a digit; if a letter or letters are present then they are in the end; optional
- `{subpart}` is a digit and optionally followed by a letter; optional
- `{year}` is a set of 4 digits; optional
- `{cor}` is a corrigendum with the pattern `Cor_{cornum}_{year}` or `COR{cornum}_{year}` where `{cornum}` is a digit; optional

2. Differences: these old and especially new sets have too many variants of patterns. It seems there aren't rules what can cover all these cases. I've tried to use [RegEx](https://regex101.com/r/ZIsvfF/2) to explore the new set but the expression becomes monstrously. It covers 99% new filenames. Does IETF have a spec for document IDs?
3. Pattern (i.) has more sense than (ii.)

Work In Progress...

**Comment by ronaldtse** [comment]
@andrew2net Thank you for the detailed analysis!

> Does IETF have a spec for document IDs?

No, they don't have a spec for machine-readable Doc IDs.

------

Considerations:

1. The old `bibxml-ieee` (252 records, Type i pattern) set is a significantly smaller subset of the `bibxml-ieee-new` set (3835 records, Type ii pattern). So "Type i" is not representative of the IEEE library.
2. There are filenames here that don't actually reflect reality: `First_Edition_2007-07_IEEE_930|Battery_Life_Improvement`. These patterns don't even show up in the actual IEEE document page or the IEEE DOI. 
3. While "Type i" deals with multiple publishers (IEEE/ISO/IEC, e.g. `reference.IEEE.ISO_IEC_42010_IEEE_STD_1471_2000_FIRST_EDITION_2007_07_15.xml`), the "Type ii" pattern incorporates them as native IEEE (e.g. `reference.IEEE.42010-2011.xml`)

I think the conclusion is this:

* We need to support the old naming scheme ("Type i" pattern) in the BibXML service (ping @strogonoff @yablokov ). No one uses "Type ii" files so we should ignore them in the pattern.

* The patterns in "Type i" and "Type ii" make **some** sense, but are not fully logical. There are too many examples like `reference.IEEE.Nuclear_EQ_Sourcebook:.xml` (Type ii) or `reference.IEEE.3006HistoricalData-2012.xml` (Type ii).
    * Therefore, for consistency and correctness reasons, we **should not** use them as the basis for the filename pattern of bibxml files in `bibxml-data-ieee`.

* Thus we should develop a **logical filename pattern** for IEEE documents, just like what we did for NIST PubID's machine-readable form. This means we need to develop a pattern for the Relaton-IEEE model (https://github.com/relaton/relaton-model-ieee)

------

Given the conclusion we need to do the following:

1. Update the Relaton IEEE model to fully implement the metadata needed for BibXML.
2. Develop a machine-readable / filename pattern for IEEE documents just like we did for NIST PubID.
3. Write out BibXML files about IEEE documents using the IEEE PubID.

@andrew2net does this sound reasonable?

**Comment by andrew2net** [comment]
> 1. Update the Relaton IEEE model to fully implement the metadata needed for BibXML.

@ronaldtse I don't think the IEEE model needs to be updated to support BibXML. I've implemented `RelatonBib::BibliongraphicItem#to_bibxml` method and `RelatonBib::BibXMLParser` module in the `relaton-bib` gem. Since every `relaton-*` flavor gem inherits a model from the `relaton-bib` gem, they can export to BibXML format and use `BibXMLParcer`.

**Comment by andrew2net** [comment]
> @andrew2net the filename pattern is produced here:
> 
> https://trac.ietf.org/trac/xml2rfc/browser/website/rfcs/bibxml/bibxml-ieee/gen-bibxml-ieee-gen-bibxml
> 
> ```python
> stdnumber = bibxml_common.get_xml_text(root, './publicationinfo/stdnumber')
> 
> ...
> 
> mod_stdnumber = re.sub('_+', '_', re.sub(r'[/,\'" ]', '_', stdnumber))
> bibxml_file = f"{args.bibxml_dir}/reference.IEEE.{mod_stdnumber}.xml"
> ```

@ronaldtse the type i uses `.` or `-` as a delimiter between number and part, and as a year prefix (`IEEE 1636.1-2013`, `IEEE.1278-1.1995`). The snippet above doesn't replace the delimiter and hence filenames are ambiguous (`reference.IEEE.1636.1_2013.xml`, `reference.IEEE.1278-1.1995.xml`). Shouldn't we replace `.` an `-` with `_` as well?
Also, the snippet doesn't replace brackets but the file name for the id `IEEE 802.1H, 1997 Edition (ISO/IEC TR11802-5:1997)` is `reference.IEEE.802.1H_1997_EDITION_ISO_IEC_TR11802_5_1997_.xml`.

**Comment by ronaldtse** [comment]
> the type i uses . or - as a delimiter between number and part, and as a year prefix (IEEE 1636.1-2013, IEEE.1278-1.1995). The snippet above doesn't replace the delimiter and hence filenames are ambiguous (reference.IEEE.1636.1_2013.xml, reference.IEEE.1278-1.1995.xml). Shouldn't we replace . an - with _ as well?
Also, the snippet doesn't replace brackets but the file name for the id IEEE 802.1H, 1997 Edition (ISO/IEC TR11802-5:1997) is reference.IEEE.802.1H_1997_EDITION_ISO_IEC_TR11802_5_1997_.xml.

We don't care about the old pattern when generating filenames. We will develop a consistent mechanism called the IEEE PubID.

**Comment by andrew2net** [comment]
@ronaldtse I suppose this issue is about generating file names. The ieee-rawbib dataset contains identifiers with different delimiters. Some of the identifiers use `.` to separate number and part, some `-` or breakspace. Years and subparts also use different separators.
As I understand we need consistent filenames to be able to find the documents by references. My suggestion is to replace all the delimiters in an identifier with `_` to generate a filename. We can generate a filename from a reference doing the same replacement in it.

**Comment by ronaldtse** [comment]
> I suppose this issue is about generating file names

The issue is **not** to generate filenames but a canonical document identifier for every IEEE document.

**Comment by andrew2net** [comment]
@ronaldtse the identifiers for most documents are generated. As I remember, for the rest IDs we have another issue.
Can we close this issue?

**Comment by ronaldtse** [comment]
Yes indeed. Thanks @andrew2net !

**Comment by strogonoff** [comment]
> The issue is **not** to generate filenames but a canonical document identifier for every IEEE document.

For the record:

1. The issue of canonical IDs for bibliographic items is real (https://github.com/ietf-ribose/bibxml-service/issues/66), there’s an ongoing discussion.
2. BibXML service (don’t know about others) phased out using filenames as canonical identifiers, though.
    - Filenames can change and are implementation details.
    - Multiple sources can provide data for the same logical bibliographic item (BibXML service handles source data merging and relies on document identifiers for that), and we cannot rely on them having consistent filenames.

(That said, consistency in case of filenames always helps.)

**Comment by ronaldtse** [comment]
Agree wholehearted with 2.
